---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: default
  labels:
    app: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      serviceAccountName: simple-sa
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: default
spec:
  selector:
    app: simple
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
